name: Deploy github pages

on: workflow_dispatch

jobs:
  build-doc:
    uses: ./.github/workflows/build-doc.yml
  build-gh-pages:
    runs-on: ubuntu-latest
    needs: build-doc
    env:
      CIM_1: CGMES_2.4.13_18DEC2013
      CIM_2: CGMES_2.4.15_16FEB2016
      CIM_3: CGMES_2.4.15_27JAN2020
      CIM_4: CGMES_3.0.0
    steps:
    - name: Download
      uses: actions/download-artifact@v4
    - name: Copy
      run: |
          mkdir -p ./copy_files/docs
          cp -r ./doc_${{env.CIM_1}} ./copy_files/docs/${{env.CIM_1}}
          cp -r ./doc_${{env.CIM_2}} ./copy_files/docs/${{env.CIM_2}}
          cp -r ./doc_${{env.CIM_3}} ./copy_files/docs/${{env.CIM_3}}
          cp -r ./doc_${{env.CIM_4}} ./copy_files/docs/${{env.CIM_4}}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./copy_files
        force_orphan: true
        keep_files: false
        publish_branch: gh-pages
