name: build-src

on: push

jobs:
  build-src:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schema:
        - CGMES_2.4.13_18DEC2013
        - CGMES_2.4.15_16FEB2016
        - CGMES_2.4.15_27JAN2020
        - CGMES_3.0.0
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{matrix.schema}}
    - name: Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{matrix.schema}}/
      run: |
          cmake ../.. -DUSE_CIM_VERSION=${{matrix.schema}}
          make -j4
