name: build-src

on: push

jobs:

  build-src-CGMES_2-4-15_27JAN2020:
    runs-on: ubuntu-latest
    env:
      USE_CIM_VERSION: CGMES_2.4.15_27JAN2020
    steps:
    - uses: actions/checkout@v3    
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Doxygen
      run: sudo apt-get install doxygen 
      shell: bash 
    - name: Install Graphviz
      run: sudo apt-get install graphviz
      shell: bash 
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}
      
    - name: Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/
      run: |
          cd ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}} 
          cmake ../.. -DUSE_CIM_VERSION=${{env.USE_CIM_VERSION}}
          make -j4
